# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weldlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weld',
            name='pipe_thickness',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
