# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weldlog', '0002_auto_20170823_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weld',
            name='disposition',
            field=models.CharField(choices=[('NA', ''), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NA',
                                   max_length=3),
        ),
    ]
