# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weldlog', '0003_auto_20170823_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='welder',
            name='procedures',
            field=models.CharField(choices=[('WPS1', 'WPS1'), ('WPS2', 'WPS')], default='WPS1', max_length=4),
        ),
    ]
