# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('weldlog', '0004_welder_procedures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welder',
            name='procedures',
        ),
    ]
