# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weldlog', '0005_remove_welder_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='welder',
            name='procedures',
            field=models.CharField(choices=[('WPS1', 'WEPS1'), ('WPS2', 'WEPS2')], default='WPS1', max_length=3),
        ),
    ]
