# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldlog', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='weld',
            name='line_number',
            field=models.CharField(default='193-HG-1500-4"', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='line_strength',
            field=models.CharField(default='900', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='material_type',
            field=models.CharField(default='CS', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='rt',
            field=models.CharField(default='100%', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='weld_type',
            field=models.CharField(default='BW', max_length=150),
        ),
        migrations.AlterField(
            model_name='welder',
            name='procedures',
            field=models.CharField(choices=[('WPS1', 'WPS1'), ('WPS2', 'WPS2')], default='WPS1', max_length=4),
        ),
    ]
