# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldlog', '0008_auto_20171102_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weld',
            name='line_number',
            field=models.CharField(default='193-HG-1500-4', max_length=150),
        ),
    ]
