# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldlog', '0009_auto_20171103_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(default='', max_length=150)),
                ('drawing', models.FileField(upload_to='')),
                ('revision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nde_type', models.CharField(choices=[('', ''), ('VT', 'VT'), ('RT', 'RT'), ('AUT', 'AUT'), ('UT', 'UT'), ('PT', 'PT'), ('MT', 'MT')], default='', max_length=3)),
                ('nde_company', models.CharField(default='', max_length=60)),
                ('nde_identifier', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Wps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_low_size', models.IntegerField(default=0)),
                ('od_high_size', models.IntegerField(default=0)),
                ('wt_low', models.FloatField(default=0)),
                ('wt_high', models.FloatField(default=0)),
                ('grade', models.CharField(default='', max_length=25)),
                ('process', models.CharField(default='', max_length=30)),
                ('code', models.CharField(choices=[('API 1104', 'API 1104'), ('ASME IX', 'ASME IX'), ('D1.1', 'D1.1'), ('', '')], default='', max_length=50)),
                ('pwht', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='city',
        ),
        migrations.RemoveField(
            model_name='weld',
            name='welders',
        ),
        migrations.AddField(
            model_name='weld',
            name='comments',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='cutout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weld',
            name='grade_a',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='grade_b',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='heat_a',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='heat_b',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='material_a',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='material_b',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='nde_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 3, 18, 47, 26, 110911)),
        ),
        migrations.AddField(
            model_name='weld',
            name='nde_number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weld',
            name='weld_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 3, 18, 47, 26, 110877)),
        ),
        migrations.AddField(
            model_name='welder',
            name='project',
            field=models.ManyToManyField(to='weldlog.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='weld',
            name='number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='welder',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.RemoveField(
            model_name='welder',
            name='procedures',
        ),
        migrations.AlterField(
            model_name='welder',
            name='stencil',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='drawings',
            name='project',
            field=models.ManyToManyField(to='weldlog.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='wps',
            field=models.ManyToManyField(to='weldlog.Wps'),
        ),
        migrations.AddField(
            model_name='weld',
            name='nde_info',
            field=models.ManyToManyField(to='weldlog.Nde'),
        ),
        migrations.AddField(
            model_name='weld',
            name='wps',
            field=models.ManyToManyField(to='weldlog.Wps'),
        ),
        migrations.AddField(
            model_name='welder',
            name='procedures',
            field=models.ManyToManyField(to='weldlog.Wps'),
        ),
    ]
