# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weldlog', '0010_auto_20171103_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='weld',
            name='welders',
            field=models.ManyToManyField(to='weldlog.Welder'),
        ),
        migrations.AlterField(
            model_name='weld',
            name='nde_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 3, 19, 12, 9, 445320)),
        ),
        migrations.AlterField(
            model_name='weld',
            name='weld_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 3, 19, 12, 9, 445289)),
        ),
    ]
